export enum PageUrls {
  HOME = "/",
  SEARCH = "/search",
  LOGIN = "/accounts/login",
  LOGOUT = "/accounts/logout",
  REGISTER = "/accounts/register",
  ADD_POST = "/compose/post",
  EDIT_POST = "/edit",
  SETTINGS = "/accounts/settings",
  CHANGE_PASSWORD = "/accounts/settings/change-password",
  EDIT_PROFILE = "/accounts/settings/edit-profile",
  THEMES = "/accounts/settings/themes",
  NOTIFICATIONS = "/accounts/notifications",
  FOLLOW_REQUESTS = "/accounts/follow-requests",
  FOLLOWERS = "/followers",
  FOLLOWING = "/following",
}
